### PR TITLE
Feature/trex

### PR DESCRIPTION
**Pull request by amirh-khali**

### CODE REVIEW

**Comment by m4tt72** [comment]
Thanks @amirh-khali for the submission 🙏🏻 

Before reviewing this PR, can you please provide a description as to what it does?

**Comment by amirh-khali** [comment]
> Thanks @amirh-khali for the submission 🙏🏻
> 
> Before reviewing this PR, can you please provide a description as to what it does?

Sure,

I just added a new command called trex. When you enter this command, a simple game similar to Chrome’s T-Rex will be shown. 
It features a score counter, a T-Rex that can jump with the space key, and a single tree that moves from the right to the left side of the screen at a constant speed. 
The color of the game changes with the terminal theme. When you lose, the game will disappear and your final score will be displayed.

**Comment by m4tt72** [comment]
@amirh-khali can you please remove any unnecessary code changes? Like linter and code style changes? just let the project's linter handle the style of the code. It makes review a lot simpler

**Comment by amirh-khali** [comment]
> @amirh-khali can you please remove any unnecessary code changes? Like linter and code style changes? just let the project's linter handle the style of the code. It makes review a lot simpler

**Pull request closed without merging**
