### PR TITLE
feat: add navigate through the arrows to previous commands

### PR DESCRIPTION
**Pull request by MatheusKProt**
tela

#2

### CODE REVIEW

**Comment by lucaspeferreira** [comment]
Nice!

**Comment by m4tt72** [comment]
@MatheusKProt Please submit functional changes only.
I added prettier config that might help your IDE pickup the correct code style used in the project.

**Comment by MatheusKProt** [comment]
@m4tt72 sure!

**Comment by MatheusKProt** [comment]
@m4tt72 done!

**Review by m4tt72 — APPROVED** [review]

**Comment by m4tt72** [comment]
Thanks @MatheusKProt, merged 🚀

**Pull request merged**
